### ISSUE TITLE
do you have the paper about your algorithm?

### ISSUE THREAD

**Issue by wangyueyun1221** [billyauhk/cloudless2#1]
can you tell me the paper name of your algorithm?

**Comment by billyauhk** [comment]
Sorry for the late reply.
Simple Answer: No paper was used.

This repo is a (abandoned?) on-going work upgrading the billyauhk/cloudless which get its idea from a MapBox blog post:
https://blog.mapbox.com/cloudless-atlas-with-landsat-142960966038
https://www.wired.com/2013/05/a-cloudless-atlas/

This simple sorting which empirically removes cloud which is put in use in the literature for long. The cloudless repo was a trial of that idea using MODIS data. The weak point of that is is could not remove shadow, or handling places which are always foggy, e.g. SiChuan plain.

Definitely one could upgrade that to better resolution imagery from Landsat 8 (thus some radiance calibration code here, from scratch) and that's why this repo (cloudless2) was created. However MapBox have made much progress on building their own pipeline and incorporating even better (paid) satellite images...do checkout "Charlie Loyd" on MapBox blog. They have already do all the Landsat images, removing cloud shadows and more.

Somehow I have lost the leisure time and CPU+HDD capacity to handle this project (and moved on to other works). It seems to me that you was publishing a paper on this area. May I have the link when it is published?
